apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-finance-configmap
data:
  DATASOURCE_HOST: postgres-hf:5432
  SCHEMA: finance
  BOOTSTRAP_SERVERS: kafka-broker-service:9092
  ROOT_LOG_LEVEL: INFO
  APP_LOG_LEVEL: DEBUG
  HOSPITAL_USERS_HOST: hospital-users-service:8090
  SERVER_PORT: '8082'